<br><br>
<font size="6"><b>Optimization for Machine Learning</b></font>

<br><br>
<div class=pull-right>
By Prof. Seungchul Lee<br>
http://iai.postech.ac.kr/<br>
Industrial AI Lab at POSTECH
</div>

# 1. Optimization

- an important tool in 1) engineering problem solving and 2) decision science


- optimize

<center><img src="./image_files/people_opt.png" width = 400 ></center>


__3 key components__
1. objective
2. decision variable or unknown
3. constraints

__Procedures__
1. The process of identifying objective, variables, and constraints for a given problem is known as "modeling"
2. Once the model has been formulated, optimization algorithm can be used to find its solutions.

__In mathematical expression__

<br>
$$\begin{align*}
\min_{x} \quad &f(x) \\
\text{subject to} \quad &g_i(x) \leq 0, \qquad i=1,\cdots,m
\end{align*}
$$


$\;\;\; $where

- $x=\begin{bmatrix}x_1 \\ \vdots \\ x_n\end{bmatrix} \in \mathbb{R}^n$ is the decision variable


- $f: \mathbb{R}^n \rightarrow \mathbb{R}$ is an objective function


- Feasible region: $\mathcal{C} = \{x: g_i(x) \leq 0. \quad i=1,
\cdots,m\}$

<br><br>
Remarks) equivalent

$$\begin{align*}
\min_{x}  f(x) \quad&\leftrightarrow \quad \max_{x} -f(x)\\
\quad g_i(x) \leq 0\quad&\leftrightarrow \quad -g_i(x) \geq 0\\
h(x) = 0 \quad&\leftrightarrow \quad 
\begin{cases}
  h(x) \leq 0 \quad \text{and} \\
  h(x) \geq 0 
\end{cases}
\end{align*}
$$

# 2. Solving Optimization Problems

- Starting with the unconstrained, one dimensional case

<br>
<center><img src="./image_files/optprob1D.png" width = 350 ></center><br>


- To find minimum point $x^*$, we can look at the derivave of the function $f'(x)$: 
    - Any location where $f'(x)$ = 0 will be a "flat" point in the function
   
   
   
- For convex problems, this is guaranteed to be a minimum


- Generalization for multivariate function $f:\mathbb{R}^n \rightarrow \ \mathbb{R}$

    - The gradient of $f$ must be zero

$$ \nabla _x f(x) = 0$$


- Gradient is a n-dimensional vector containing partial derivatives with respect to each dimension

<br>
$$
x = \begin{bmatrix}
x_1 \\
x_2 \\
\vdots \\
x_n
\end{bmatrix} \quad \quad \quad \quad \nabla _x f(x) = \begin{bmatrix}
\partial f(x) \over \partial x_1 \\
\vdots\\
\partial f(x) \over \partial x_n
\end{bmatrix}
$$

<br>
- For continuously differentiable $f$ and unconstrained optimization, optimal point must have $\nabla _x f(x^*)=0$

## 2.1. How To Find $\nabla _x f(x) = 0$: Analytic Approach

- Direct solution

    - In some cases, it is possible to analytically compute $x^*$ such that $ \nabla _x f(x^*)=0$

<br>
$$ 
\begin{align*}
f(x) &= 2x_1^2+ x_2^2 + x_1 x_2 -6 x_1 -5 x_2\\\\
\Longrightarrow \nabla _x f(x) &= \begin{bmatrix}
4x_1+x_2-6\\
2x_2 + x_1 -5
\end{bmatrix} = \begin{bmatrix}0\\0 \end{bmatrix}\\\\
\therefore x^* &= \begin{bmatrix}
4 & 1\\
1 & 2
\end{bmatrix} ^{-1} \begin{bmatrix}
6 \\ 5\\
\end{bmatrix} = \begin{bmatrix}
1 \\ 2\\
\end{bmatrix}
\end{align*}
$$


## 2.2. How To Find $\nabla _x f(x) = 0$: Iterative Approach

- <font color='red'>Iterative methods</font>

   - More commonly the condition that the gradient equal zero will not have an analytical solution, require iterative methods
    
<br><br>    
<center><img src="./image_files/iterativemethods.png" width = 350 ></center>
<br><br>

- The gradient points in the direction of "steepest ascent" for function $f$

### 2.2.1. Gradient Descent

- It motivates the gradient descent algorithm, which repeatedly takes steps in the direction of the negative gradient

<br>
$$ x \leftarrow x - \alpha \nabla _x f(x) \quad \quad \text{for some step size } \alpha > 0$$

<br><br>
<center><img src="./image_files/descentdir1d.png" width = 800 ></center>

- Gradient Descent

$$\text{Repeat : } x \leftarrow x - \alpha \nabla _x f(x) \quad \quad \text{for some step size } \alpha > 0$$ 

<br><br>
<center><img src="./image_files/graddesc.png" width = 400 ></center>

- Gradient Descent in Higher Dimension


$$\text{Repeat : } x \leftarrow x - \alpha \nabla _x f(x)$$

<br><br><br>
<center><img src="./image_files/graddescinhigh.png" width = 900 ></center>
<br><br>

### 2.2.2. Choosing Step Size 

- Learning rate

<br><br>
<center><img src="./image_files/ChoosingStep.png" width = 800 ></center>

### 2.2.3 Where will We Converge?

<br><br><br>

<center><img src="./image_files/wherewillweconv.png" width = 650 ></center>

$\qquad \qquad \qquad \qquad \qquad \qquad \qquad \qquad \qquad \qquad \qquad \qquad \quad \qquad \qquad \bullet \, \text{Random initialization}$

$\qquad \qquad \qquad \qquad \qquad \qquad \qquad \qquad \qquad \qquad \qquad \qquad \quad \qquad \qquad \bullet \, \text{Multiple trials}$


### 2.2.4. Example

<br>
$$
\begin{align*}
\min& \quad (x_1-3)^{2} + (x_2-3)^{2}\\\\
=\min& \quad \frac{1}{2} \begin{bmatrix} x_1 & x_2 \end{bmatrix}
\begin{bmatrix} 2 & 0 \\ 0 & 2 \end{bmatrix}
\begin{bmatrix} x_1 \\ x_2 \end{bmatrix} - 
\begin{bmatrix} 6 & 6 \end{bmatrix}
\begin{bmatrix} x_1 \\ x_2 \end{bmatrix} + 18
\end{align*}
$$

<br><br>

\begin{align*}
f &= \frac{1}{2}X^THX + g^TX \\
\nabla f &= HX+g
\end{align*}

- update rule

$$ X_{i+1} = X_{i} - \alpha_i \nabla f(X_i)$$

In [1]:
import numpy as np

H = np.matrix([[2,0], [0,2]])
g = np.matrix([[6], [6]])

x = np.zeros((2,1))
alpha = 0.1

for i in range(25):    
    df = H*x + g
    x = x - alpha * df

print(x)

[[2.99999147]
 [2.99999147]]


### 2.2.5. Example

$$
\begin{align*}
\min& \quad x_1^2 + x_2^2 + x_3^2 - 6x_1 + 2x_3 + 10\\\\
=\min& \quad \frac{1}{2} \begin{bmatrix} x_1 & x_2 & x_3\end{bmatrix}
\begin{bmatrix} 2 & 0 & 0 \\ 0 & 2 & 0 \\ 0 & 0 & 2\end{bmatrix}
\begin{bmatrix} x_1 \\ x_2 \\ x_3 \end{bmatrix} + 
\begin{bmatrix} -6 & 0 & 2 \end{bmatrix}
\begin{bmatrix} x_1 \\ x_2 \\ x_3 \end{bmatrix} + 10
\end{align*}
$$

<br><br>

\begin{align*}
f &= \frac{1}{2}X^THX + g^TX \\
\nabla f &= HX+g
\end{align*}

- update rule

$$ X_{i+1} = X_{i} - \alpha_i \nabla f(X_i)$$

In [2]:
H = np.array([[2,0,0], 22])
f = 

x =  
alpha = 

for i in range(25):    
    g = 
    x = 

print(x)

[[ 2.99999147]
 [ 0.        ]
 [-0.99999716]]


### 2.2.6. Example

<br>
$$
\begin{array}{Icr}\begin{align*}
\max_{x} \quad & 3x_1 + {3 \over 2}x_2 \\
\text{subject to} \quad
& -1 \leq x_1 \leq 2 \\
& \quad 0 \leq x_2 \leq 3
\end{align*}\end{array}
\quad\implies\quad
\begin{array}{I}
\quad \min_{x} \quad & - \begin{bmatrix} 3 \\ 3 / 2 \end{bmatrix}^T \begin{bmatrix} x_1 \\ x_2 \end{bmatrix} \\
\text{subject to} \quad
& \begin{bmatrix} -1 \\ 0 \end{bmatrix} \leq \begin{bmatrix} x_1 \\ x_2 \end{bmatrix} \leq \begin{bmatrix} 2 \\ 3 \\ \end{bmatrix}
\end{array}
$$

In [3]:
f = 

x = 
alpha = 

lb = 
ub = 

for i in range(25): 
    x = 
    
    # lb constraints 
    lb_TF = 
    x = 
    
    # ub constraints 
    ub_TF = 
    x = 
    
print(x)

[[2.]
 [3.]]


In [4]:
%ewwqerqwerwe%javascript
$.getScript('https://kmahelona.github.io/ipython_notebook_goodies/ipython_notebook_toc.js')

<IPython.core.display.Javascript object>